name: Publish and Deploy App
author: Tiago Freire <freire.tiago@gmail.com>
description: An action that publishes and deploys a VTEX IO app after release
branding:
  icon: 'box'
  color: 'purple'

inputs:
  appKey:
    description: "App key to login with VTEX Toolbelt"
    required: true
  appToken:
    description: "App token to login with VTEX Toolbelt"
    required: true
  toolbelt-workspace:
    description: "Workspace to start after login, default master"
    required: false
    default: master

runs:
  using: "composite"
  steps:
    - name: Checkout app source
      uses: actions/checkout@v4

    - name: Load manifest.json
      run: |
        echo "MANIFEST_JSON<<EOF" >> $GITHUB_ENV
        cat ./manifest.json >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Load app metadata
      run: |
        APP_VENDOR=${{ fromJson(env.MANIFEST_JSON).vendor }}
        echo "APP_VENDOR=$APP_VENDOR" >> $GITHUB_ENV
        APP_NAME=${{ fromJson(env.MANIFEST_JSON).name }}
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
        APP_VERSION=${{ fromJson(env.MANIFEST_JSON).version }}
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        APP_FULL_NAME=$APP_VENDOR.$APP_NAME@$APP_VERSION
        echo "APP_FULL_NAME=$APP_FULL_NAME" >> $GITHUB_ENV
        echo -e "✅ App ${{ env.APP_FULL_NAME }} found."
      shell: bash

    - name: Install VTEX Toolbelt
      run:  curl -L https://vtex.io/vtexcli/install | sh
      shell: bash

    - name: Check VTEX Toolbelt version
      run: vtex version
      shell: bash

    - name: VTEX Toolbelt authentication
      run: bash ${{ github.action_path }}/scripts/toolbelt-entrypoint.sh
      env:
        VTEX_AUTHENTICATE: "true"
        VTEX_ACCOUNT: ${{ env.APP_VENDOR }}
        VTEX_APP_KEY: ${{ inputs.appKey }}
        VTEX_APP_TOKEN: ${{ inputs.appToken }}
        VTEX_WORKSPACE: ${{ inputs.toolbelt-workspace }}
      shell: bash

    - name: Publish app ${{ env.APP_FULL_NAME }}
      run: |
        yes | vtex publish --force 2>&1 | tee publish.log || true
        if ! grep -q "published successfully" publish.log; then
          echo -e "\n❌ Failed to publish app ${{ env.APP_FULL_NAME }}."
          exit 1
        fi
        echo "✅ App published successfully."
      shell: bash

    - name: Deploy app ${{ env.APP_FULL_NAME }}
      run: |
        yes | vtex deploy --yes --force 2>&1 | tee deploy.log || true
        if ! grep -q "Successfully deployed" deploy.log; then
          echo -e "\n❌ Failed to deploy app ${{ env.APP_FULL_NAME }}."
          exit 1
        fi
        echo "✅ App deployed successfully."
      shell: bash

    - name: Create GitHub release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="$tag" \
          --generate-notes
      shell: bash
