name: Publish and Deploy App
author: Tiago Freire <freire.tiago@gmail.com>
description: An action than publishes and deploys a VTEX IO app after release
inputs:
  appKey:
    required: true
    type: string
  appToken:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Load manifest.json
      run: |
        echo "MANIFEST_JSON<<EOF" >> $GITHUB_ENV
        cat ./manifest.json >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Load vendor, name and version
      run: |
        APP_VENDOR=${{ fromJson(env.MANIFEST_JSON).vendor }}
        echo "APP_VENDOR=$APP_VENDOR" >> $GITHUB_ENV
        APP_NAME=${{ fromJson(env.MANIFEST_JSON).name }}
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
        APP_VERSION=${{ fromJson(env.MANIFEST_JSON).version }}
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        APP_FULL_NAME=$APP_VENDOR.$APP_NAME@$APP_VERSION
        echo "APP_FULL_NAME=$APP_FULL_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Authenticate
      uses: vtex/action-toolbelt@v8
      with:
        account: ${{ env.APP_VENDOR }}
        appKey: ${{ inputs.appKey }}
        appToken: ${{ inputs.appToken }}

    - name: Publish App
      run: |
        echo -e "\n=============== Publish app ${{ env.APP_FULL_NAME }}\n"
        output=$(vtex publish)
        echo "$output"
        if [[ $output != *"published successfully"* ]]; then
          echo -e "\nFailed to publish app."
          exit 1
        fi
      shell: bash

    - name: Deploy App
      run: |
        echo -e "\n=============== Deploy app ${{ env.APP_FULL_NAME }}\n"
        output=$(vtex deploy --force)
        echo "$output"
        if [[ $output != *"Successfully deployed"* ]]; then
          echo -e "\nFailed to deploy app."
          exit 1
        fi
      shell: bash
