name: Publish and Deploy App
author: Tiago Freire <freire.tiago@gmail.com>
description: An action than publishes and deploys a VTEX IO app after release
branding:
  icon: 'box'
  color: 'purple' 
inputs:
  appKey:
    description: "App key to login with VTEX Toolbelt"
    required: true
  appToken:
    description: "App token to login with VTEX Toolbelt"
    required: true
  toolbelt-workspace:
    description: "Workspace to start after login, default master"
    required: false
    default: master
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: |
        echo "::group::Load manifest.json"
        echo "MANIFEST_JSON<<EOF" >> $GITHUB_ENV
        cat ./manifest.json >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "::endgroup::"
      shell: bash

    - run: |
        echo "::group::Load vendor, name and version"
        APP_VENDOR=${{ fromJson(env.MANIFEST_JSON).vendor }}
        echo "APP_VENDOR=$APP_VENDOR" >> $GITHUB_ENV
        APP_NAME=${{ fromJson(env.MANIFEST_JSON).name }}
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
        APP_VERSION=${{ fromJson(env.MANIFEST_JSON).version }}
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        APP_FULL_NAME=$APP_VENDOR.$APP_NAME@$APP_VERSION
        echo "APP_FULL_NAME=$APP_FULL_NAME" >> $GITHUB_ENV
        echo "::endgroup::"
      shell: bash

    - name: "Install VTEX Toolbelt"
      run: |
        echo "::group::Global installation"
        curl -L https://vtex.io/vtexcli/install | sh
        echo "::endgroup::"
        echo "::group::Check version"
        vtex version
        echo "::endgroup::"
      shell: bash

    - name: "Authentication"
      run: bash ${{ github.action_path }}/scripts/toolbelt-entrypoint.sh
      env:
        VTEX_AUTHENTICATE: "true"
        VTEX_ACCOUNT: ${{ env.APP_VENDOR }}
        VTEX_APP_KEY: ${{ inputs.appKey }}
        VTEX_APP_TOKEN: ${{ inputs.appToken }}
        VTEX_WORKSPACE: ${{ inputs.toolbelt-workspace }}
      shell: bash

    - run: |
        echo "::group::Publish app ${{ env.APP_FULL_NAME }}"
        output=$(yes | vtex publish --force)
        echo "$output"
        if [[ $output != *"published successfully"* ]]; then
          echo -e "\nFailed to publish app."
          exit 1
        fi
        echo "::endgroup::"
      shell: bash

    - run: |
        echo "::group::Deploy app ${{ env.APP_FULL_NAME }}"
        output=$(yes | vtex deploy --force)
        echo "$output"
        if [[ $output != *"Successfully deployed"* ]]; then
          echo -e "\nFailed to deploy app."
          exit 1
        fi
        echo "::endgroup::"
      shell: bash

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
        tag: ${{ github.ref_name }}
      run: |
        echo "::group::Create release $tag"
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$tag" \
            --generate-notes
        echo "::endgroup::"
      shell: bash